import logging
import os
import sys
import re
from datetime import datetime

# Configure logger
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        # Log to a file specific to this version of the script
        logging.FileHandler("code_copy/code_copy_main_and_templates.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

SENSITIVE_PATTERNS = re.compile(r"(key|secret|password|token|sid|auth_token)", re.IGNORECASE)

def read_file_contents(file_path):
    """Reads and returns the contents of a file safely, masking sensitive values in .env."""
    try:
        logger.debug(f"Reading file: {file_path}")

        with open(file_path, 'r', encoding='utf-8', errors='ignore') as file: # Added errors='ignore' for robustness
            lines = file.readlines()

        # Mask sensitive values only for .env files found at the root
        if os.path.basename(file_path) == ".env" and os.path.dirname(file_path) == SOURCE_DIRECTORY:
            logger.info(f"Masking sensitive data in root .env file: {file_path}")
            for i in range(len(lines)):
                line = lines[i].strip()
                if "=" in line:
                    key, value = line.split("=", 1)
                    if SENSITIVE_PATTERNS.search(key) and value.strip():
                        lines[i] = f"{key}=XXX\n"
        elif file_path.endswith(".env"): # Log if other .env files are found but not masked by this specific rule
            logger.warning(f"Found .env file not at root, not masking: {file_path}")


        return "".join(lines)

    except Exception as e:
        logger.error(f"Error reading file {file_path}: {e}")
        return f"\n[ERROR: Could not read {file_path}]\n"

def create_output_file():
    """Creates a timestamped output file in the code_copy folder."""
    # Ensure the code_copy directory exists
    if not os.path.exists("code_copy"):
        os.makedirs("code_copy")
        logger.info("Created 'code_copy' directory.")

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    # Updated filename to reflect specific content
    return f"code_copy/main_and_templates_contents_{timestamp}.txt"

# Global variable to store the source folder, set in process_folder
SOURCE_DIRECTORY = ""

def process_folder(source_folder_param):
    """
    Reads and writes only files directly in the source_folder (root)
    and all files directly within a 'templates' subdirectory if it exists.
    """
    global SOURCE_DIRECTORY
    SOURCE_DIRECTORY = source_folder_param # Set the global for read_file_contents

    output_file = create_output_file()
    logger.info(f"Saving selected files from '{SOURCE_DIRECTORY}' and its 'templates' subdirectory to: {output_file}")

    try:
        with open(output_file, 'w', encoding='utf-8') as out_file:
            out_file.write(f"Contents of files in '{SOURCE_DIRECTORY}' (root) and '{os.path.join(SOURCE_DIRECTORY, 'templates')}'\n")
            out_file.write("=" * 80 + "\n\n")

            # 1. Process files directly in the source_folder (root)
            logger.info(f"Processing files in root directory: {SOURCE_DIRECTORY}")
            for item_name in sorted(os.listdir(SOURCE_DIRECTORY)):
                item_path = os.path.join(SOURCE_DIRECTORY, item_name)

                # Skip directories other than 'templates' for now
                if os.path.isdir(item_path) and item_name != "templates":
                    logger.debug(f"Skipping directory in root: {item_path} (not 'templates')")
                    continue

                if os.path.isfile(item_path):
                    # Skip common non-code/config files in root
                    if item_name.startswith("log_") or \
                       item_name.endswith((".pyc", ".log", ".db", ".sqlite3", ".txt")) and not item_name == "fees.txt" and not item_name == "requirements.txt" : # Allow fees.txt and requirements.txt
                        if item_name != os.path.basename(output_file) and item_name != "code_copy_main_and_templates.log": # Don't skip the log generated by this script or the output file itself
                            logger.debug(f"Skipping common non-code file in root: {item_path}")
                            continue

                    logger.info(f"Processing root file: {item_path}")
                    out_file.write(f"FILE: {item_path}\n")
                    out_file.write("-" * 80 + "\n")
                    content = read_file_contents(item_path)
                    out_file.write(content)
                    out_file.write("\n\n" + "=" * 80 + "\n\n")

            # 2. Process files in the 'templates' subdirectory if it exists
            templates_dir_path = os.path.join(SOURCE_DIRECTORY, "templates")
            if os.path.exists(templates_dir_path) and os.path.isdir(templates_dir_path):
                logger.info(f"Processing files in templates directory: {templates_dir_path}")
                for template_filename in sorted(os.listdir(templates_dir_path)):
                    template_file_path = os.path.join(templates_dir_path, template_filename)
                    if os.path.isfile(template_file_path): # Ensure it's a file
                        logger.info(f"Processing template file: {template_file_path}")
                        out_file.write(f"FILE: {template_file_path}\n")
                        out_file.write("-" * 80 + "\n")
                        content = read_file_contents(template_file_path) # .env masking is specific to root .env
                        out_file.write(content)
                        out_file.write("\n\n" + "=" * 80 + "\n\n")
            else:
                logger.info("No 'templates' directory found or it's not a directory.")

        logger.info(f"Successfully created output file: {output_file}")

    except Exception as e:
        logger.error(f"Error creating output file: {e}")

if __name__ == "__main__":
    # Determine the folder to process: script's arg or current working directory
    folder_to_process = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    # Ensure the path is absolute for clarity and consistency
    absolute_folder_path = os.path.abspath(folder_to_process)

    logger.info(f"Targeting folder: {absolute_folder_path}")
    process_folder(absolute_folder_path)